swagger: "2.0"

info:
  title: "Python MS Monitor"
  version: "1.0"

basePath: /monitor

schemes:
 - http
paths:
  /ping:
    get:
      operationId: servicemesh.monitor.ping
      responses:
        '200':
          description: 'OK'
