---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  syslog:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/sys.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  hummber_gang_chat:
    level: INFO
    handlers: [info_file_handler, error_file_handler]
    propagate: no

  #
  #==================================================
  #               containers
  #==================================================
  #
  tornado.access:
    level: INFO
    handlers: [info_file_handler, error_file_handler]
    propagate: no

  tornado.application:
    level: WARN
    handlers: [info_file_handler, error_file_handler]
    propagate: no

  tornado.general:
    level: WARN
    handlers: [info_file_handler, error_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, syslog, info_file_handler, error_file_handler]
...
